image: docker
services:
  - docker:dind

stages:
  - testing
  - deployment

test:
  stage: testing
  only:
    - main
  script:
    - echo TODO:Testing

deploy:
  stage: deployment
  interruptible: true
  only:
    - main
  script:
    - touch .env
    - echo ${ENV} > .env
    - sudo apt-get install -y python3-pip
    - sudo pip3 install --upgrade setuptools
    - sudo pip3 install docker-compose
    - sudo docker-compose  build
    - sudo docker-compose up -d
  environment: production
